apiVersion: sources.knative.dev/v1alpha1
kind: DockerHubSource
metadata:
  name: dockerhub-source
spec:
  disableAutoCallback: true
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: normal-display
