/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	sourcesv1alpha1 "github.com/tom24d/eventing-dockerhub/pkg/apis/sources/v1alpha1"
	versioned "github.com/tom24d/eventing-dockerhub/pkg/client/clientset/versioned"
	internalinterfaces "github.com/tom24d/eventing-dockerhub/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/tom24d/eventing-dockerhub/pkg/client/listers/sources/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DockerHubSourceInformer provides access to a shared informer and lister for
// DockerHubSources.
type DockerHubSourceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DockerHubSourceLister
}

type dockerHubSourceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDockerHubSourceInformer constructs a new informer for DockerHubSource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDockerHubSourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDockerHubSourceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDockerHubSourceInformer constructs a new informer for DockerHubSource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDockerHubSourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DockerhubsourceV1alpha1().DockerHubSources(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DockerhubsourceV1alpha1().DockerHubSources(namespace).Watch(options)
			},
		},
		&sourcesv1alpha1.DockerHubSource{},
		resyncPeriod,
		indexers,
	)
}

func (f *dockerHubSourceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDockerHubSourceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dockerHubSourceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&sourcesv1alpha1.DockerHubSource{}, f.defaultInformer)
}

func (f *dockerHubSourceInformer) Lister() v1alpha1.DockerHubSourceLister {
	return v1alpha1.NewDockerHubSourceLister(f.Informer().GetIndexer())
}
