name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ko:
    name: Build Test with ko
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Get google/ko
        run: GO111MODULE=on go get github.com/google/ko/cmd/ko


      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build test for controller with ko
        run: ko publish ./cmd/controller -L

      - name: Build test for webhook with ko
        run: ko publish ./cmd/webhook -L

      - name: Build test for receive adapter with ko
        run: ko publish ./cmd/receive_adapter -L

      - name: Build test for e2e code
        run: go build -race -tags e2e ./test/...

  build-presubmit:
    name: Presubmit Build Test
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
      KO_DOCKER_REPO: ${{ github.repository_owner }}


    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out test-infra
        uses: actions/checkout@v2
        with:
          repository: knative/test-infra
          fetch-depth: 1
          path: ./src/knative.dev/test-infra

      - name: Install kntest
        run: |
          pushd ./src/knative.dev/test-infra
          go install ./kntest/cmd/kntest
          popd

      - name: Check out code onto GOPATH
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: ./src/github.com/tom24d/eventing-dockerhub

      - name: Run presubmit-test.sh
        run: |
          pushd ./src/github.com/tom24d/eventing-dockerhub
          ./test/presubmit-tests.sh --build-tests
          popd

