name: Test

on:
  push:
    branches: [ 'main', 'release-*' ]
  pull_request:
    branches: [ 'main', 'release-*' ]

jobs:
  build-ko:
    name: Build Test
    strategy:
      matrix:
        go-version: [1.16.x]
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Get google/ko
        run: go install github.com/google/ko@v0.8.2


      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build test for controller with ko
        run: ko publish ./cmd/controller -L

      - name: Build test for webhook with ko
        run: ko publish ./cmd/webhook -L

      - name: Build test for receive adapter with ko
        run: ko publish ./cmd/receive_adapter -L

      - name: Vet
        run: go vet ./...

      - name: Build test
        run: go build -race ./...

      - name: Build test for e2e code
        run: go build -race -tags e2e ./test/...
