name: UpdateDeps

on:
  schedule:
    - cron: '25 3 * * *'

jobs:
  update-deps:
    name: Auto Update Dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: export PATH
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        export GOPATH=$(go env GOPATH)
    
    - name: echo necessary PATH
      run: |
        echo $GOPATH

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: install hub cli
      uses: geertvdc/setup-hub@v1.0.0

    - name: Run update sh
      run: ./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh

    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GITHUB_USER: tom24d
      run: hub pull-request -b master -a tom24d -m "[CI] Auto Update Dependencies"
