name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e:
    name: Integration Test
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    env:
      GOPATH: ${{ github.workspace }}
      KO_DOCKER_REPO: ${{ github.repository_owner }}

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Get google/ko
        run: GO111MODULE=on go get github.com/google/ko/cmd/ko

      - name: Create KinD Cluster
        run: |
          GO111MODULE=on go get sigs.k8s.io/kind@v0.8.1

          cat <<EOF | kind create cluster --config=-
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane
            image: kindest/node:v1.16.9@sha256:7175872357bc85847ec4b1aba46ed1d12fa054c83ac7a8a11f5c268957fd5765
            extraPortMappings:
            - containerPort: 31080
              hostPort: 80
              protocol: TCP
            - containerPort: 31443
              hostPort: 443
              protocol: TCP
          - role: control-plane
            image: kindest/node:v1.16.9@sha256:7175872357bc85847ec4b1aba46ed1d12fa054c83ac7a8a11f5c268957fd5765
          - role: worker
            image: kindest/node:v1.16.9@sha256:7175872357bc85847ec4b1aba46ed1d12fa054c83ac7a8a11f5c268957fd5765
          - role: worker
            image: kindest/node:v1.16.9@sha256:7175872357bc85847ec4b1aba46ed1d12fa054c83ac7a8a11f5c268957fd5765
          EOF

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: ./src/github.com/tom24d/eventing-dockerhub

      - name: Install Knative Serving & Eventing
        run: |
          pushd ./src/github.com/tom24d/eventing-dockerhub
          ./test/KinD-setup.sh
          popd

      - name: Log in to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PAT }} | docker login -u ${{ github.repository_owner }} --password-stdin

      - name: Run integration test
        run: |
          pushd ./src/github.com/tom24d/eventing-dockerhub
          ./test/e2e-tests.sh --run-tests --skip-knative-setup --skip-teardowns
          popd
