name: Test

on:
  push:
    branches: [ 'master', 'release-*' ]
  pull_request:
    branches: [ 'master', 'release-*' ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  e2e:
    name: Integration Test
    strategy:
      matrix:
        go-version: [1.15.x]
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}
      KO_DOCKER_REPO: ${{ github.repository_owner }}

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Get google/ko
        run: GO111MODULE=on go get github.com/google/ko/cmd/ko

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: ./src/github.com/tom24d/eventing-dockerhub

      - name: Create KinD Cluster
        env:
          KIND_VERSION: v0.8.1
        run: |
          pushd ./src/github.com/tom24d/eventing-dockerhub
          ./test/kind/bootstrap.sh
          popd


      - name: Log in to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PAT }} | docker login -u ${{ github.repository_owner }} --password-stdin

      - name: Run integration test
        run: |
          pushd ./src/github.com/tom24d/eventing-dockerhub
          ./test/kind/run-tests.sh
          popd
