name: Test

on:
  push:
    branches: [ 'main', 'release-*' ]
  pull_request:
    branches: [ 'main', 'release-*' ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  e2e:
    name: Integration Test
    strategy:
      matrix:
        go-version: [1.18.x]
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}
      KO_DOCKER_REPO: localhost:5000

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Get google/ko
        run: go install github.com/google/ko@v0.11

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: ./src/github.com/tom24d/eventing-dockerhub

      - name: Create KinD Cluster
        run: |
          pushd ./src/github.com/tom24d/eventing-dockerhub
          ./test/kind/bootstrap.sh
          popd

      - name: Run integration test
        run: |
          pushd ./src/github.com/tom24d/eventing-dockerhub
          ./test/kind/run-tests.sh
          popd
