name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Unit Test
    strategy:
      matrix:
        go-version: [1.15.x]
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Presubmit Unit Test
      run: ./test/presubmit-tests.sh --unit-tests
