name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Unit test for v1alpha1
      run: go test ./pkg/apis/sources/v1alpha1

    - name: Unit test for adapter
      run: go test -race ./pkg/adapter/...
