name: Test

on:
  push:
    branches: [ 'main', 'release-*' ]
  pull_request:
    branches: [ 'main', 'release-*' ]

jobs:

  build:
    name: Verify-codegen
    strategy:
      matrix:
        go-version: [1.16.x]
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}

    steps:

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Get go-licenses
      run: go install github.com/google/go-licenses@latest

    - name: Check out code onto GOPATH
      uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 1
        path: ./src/github.com/tom24d/eventing-dockerhub

    - name: Verify codegen
      run: |
        pushd ./src/github.com/tom24d/eventing-dockerhub
        ./hack/verify-codegen.sh
        popd
